### ISSUE TITLE
Add support for Celery 3.1

### ISSUE THREAD

**Issue by laurentguilbert** [PolicyStat/jobtastic#33]
```AppCase``` was moved from ```celery.tests.utils``` to ```celery.tests.case```.

```eager_tasks``` is also nowhere to be found.

Since django is supported out of the box in 3.1 it's a bit tricky to handle I think. Maybe with another test project ?

I also tried running tests on Celery 3.0 but the ```CELERY_CACHE_BACKEND = 'memory'``` is unrecognized so I used ```CELERY_CACHE_BACKEND = 'locmem://'``` instead.

Then I encontered one failed test: ```test_sanity (jobtastic.tests.test_broker_fallbacks.BrokenBrokerTestCase)```.

Maybe my environement isn't properly set up though...

**Comment by edwardotis** [comment]
+1

**Comment by winhamwr** [comment]
#46 added tox environments to test against all of the combinations of Django 1.6, Django 1.7, Celery 3.0 and Celery 3.1. That should make adding/testing support for newer Celery a bit easier.

**Comment by traverseda** [comment]
+1, still a problem. Might want to update the docs to reflect that this isn't being super maintained?

**Comment by midnightlynx** [comment]
Celery 3.1 tests are all passing. Is this issue fixed, or are people still having problems with 3.1?

**Comment by winhamwr** [comment]
I'm going to close this as fixed, but if anyone has any Celery 3.1 problems, please let us know!
