### ISSUE TITLE
compatibility with Celery 4.0?

### ISSUE THREAD

**Issue by vincentschut** [PolicyStat/jobtastic#60]
Hi,

with celery 4.0 around the corner, and me needing to implement a quite complex task based processing infrastructure which would benefit greatly from jobtastic's additional features, I wonder: is jobtastic compatible with celery 4.0? Or, if not, is it planned?

Sorry if this is not the right place to ask, could not find a specific jobtastic mail list or so.

**Comment by jlward** [comment]
Hello Vincent,

We haven't done any testing with celery 4.0 yet, but it is something we definitely want to support. I think the first thing we need before we can officially support celery 4.0 is a stable version of celery 4.0 on pypi. After that, it should be as simple as updating the tox/travis files to show we support celery 4.0 and fix any bugs found. If this is something you would be interested in take a look at, we do love pull requests :) If not, we will eventually get to it.

**Comment by vincentschut** [comment]
OK, thanks, that's good to know! Then I can safely start with current Celery in combination with Jobtastic, and have no worries about a future upgrade path.
I understand your "let's wait for a 4.0 on pypi", however, many new features and even some bug fixes now already only go into celery master (=4.0rc or so). So using Celery 4.0 master is often already encouraged (at least, that's how it feels to me). But I have the feeling it won't take long before a 4.0...
Anyway, I might be able to help with testing once I start this project (and maybe bug fixing, though I don't know Celery's insides very good yet), depending on my balance between production/development at that time.

**Comment by winhamwr** [comment]
> Then I can safely start with current Celery in combination with Jobtastic, and have no worries about a future upgrade path.

We're still using Jobtastic in production, and Celery 4 has some nice goodies, so we'll build 4.0 compatibility eventually. If you wanted to create a branch/PR that runs Jobtastic against Celery 4.0 master, that would be interesting/helpful.
