### ISSUE TITLE
Project configuration

### ISSUE THREAD

**Issue by kareemyousef** [PolicyStat/jobtastic#61]
Hi, I was investigating how to get jobtastic working, and I managed to create a sample projects with two types of tasks. I could start any number of tasks concurrently. I added the EXACT SAME files to my product code base in a new package. Whenever I try to run a task, I get an exception (**_AttributeError: 'DisabledBackend' object has no attribute '_get_task_meta_for'_**). Here is the traceback:

`Traceback (most recent call last):
  File "/home/kyousef/server_sdk/SDK/inmobly_sdk/bgqueue_tasks/test.py", line 2, in <module>
    odd_task = GenerateOdd.delay_or_fail(size=20)
  File "/usr/local/lib/python2.7/dist-packages/jobtastic/task.py", line 183, in delay_or_fail
    return self.apply_async(args=args, kwargs=kwargs)
  File "/usr/local/lib/python2.7/dist-packages/jobtastic/task.py", line 256, in apply_async
    logging.info('Current status: %s', task_meta.status)
  File "/usr/local/lib/python2.7/dist-packages/celery/result.py", line 394, in state
    return self._get_task_meta()['status']
  File "/usr/local/lib/python2.7/dist-packages/celery/result.py", line 339, in _get_task_meta
    return self._maybe_set_cache(self.backend.get_task_meta(self.id))
  File "/usr/local/lib/python2.7/dist-packages/celery/backends/base.py", line 307, in get_task_meta
    meta = self._get_task_meta_for(task_id)
AttributeError: 'DisabledBackend' object has no attribute '_get_task_meta_for'`

Help will be much appreciated.

**Comment by winhamwr** [comment]
Hi Kareem,

> `AttributeError: 'DisabledBackend' object has no attribute '_get_task_meta_for')`

What version of Celery are you using?

Regardless, I think this error means that you don't have a [results backend](http://docs.celeryproject.org/en/latest/getting-started/first-steps-with-celery.html#keeping-results) configured. Jobtastic requires that you use a results backend so that we can use that to keep track of task status and other important things.

I hope that helps.

-Wes

**Comment by kareemyousef** [comment]
Hi Wes,
I'm using Celery 3.1.23 (Cipater)

I do have a results backend. As I mentioned above, the same code works on a standalone python project. This error only happens when I copy it inside my product code base. I think it has something to do with project configuration or something that I did to the standalone project and missed with my product project.

Here is my app declaration:

```
from jobtastic_odd import GenerateOdd
from celery import Celery

app = Celery('inmobly_bg_queue', backend='amqp', broker='amqp://', )
```

I run the celery service using this command:

`celery worker --loglevel=info -P processes -c 2 -A bgqueue_app`

Finally, I start the task as follows:

```
from jobtastic_odd import GenerateOdd
odd_task = GenerateOdd.delay_or_fail(size=20)
```

Thanks for the help :+1:

**Comment by winhamwr** [comment]
It definitely seems like a problem with the celery settings, but it's not jumping out at me from reading those snippets, unfortunately.

**Comment by winhamwr** [comment]
I'm going to close this, but if anyone else has suggestions for troubleshooting, feel free to comment.
