### ISSUE TITLE
celery.conf deprecated

### ISSUE THREAD

**Issue by coolacid** [PolicyStat/jobtastic#64]
https://github.com/PolicyStat/jobtastic/blob/master/jobtastic/task.py#L43 is using celery.conf however this was deprecated in 2.5. 

There does not appear to be a way to set which cache system to use in Celery from jobtastic. Without this, it appears this becomes django required. :(

**Comment by winhamwr** [comment]
I think #63 will address this, once it's merged in.

**Comment by winhamwr** [comment]
#63 is now merged in. If you get a chance, could you see if that solves your problem?
