### ISSUE TITLE
groups or subtask

### ISSUE THREAD

**Issue by a5m0** [PolicyStat/jobtastic#71]
Is it possible to use jobtastic for celery groups/subtasks? I would like to have a single jobID/progress calculator that runs a number of different queries that may be different each time but to cache these individual queries if they get called again sort of like this:

`
        result = bulk_lookup.delay_or_fail(
            queries=list_of_queries
        )
`

**Comment by winhamwr** [comment]
You could use Jobtastic in your subtasks to make sure the queries are cached, but we don't have anything to help with progress reporting across multiple tasks. The progress reporting is based on the progress of a specific job running on a specific worker.
